server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:olympic_humg_dev}
    username: ${DB_USERNAME:olympic_humg}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/api/v1/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user
            redirect-uri: "{baseUrl}/api/v1/login/oauth2/code/{registrationId}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

olympic:
  api:
    problem-type-base-url: ${OLYMPIC_API_PROBLEM_TYPE_BASE_URL:http://localhost:8080/api/v1/problems}
  client:
    base-url: ${OLYMPIC_CLIENT_BASE_URL:http://localhost:3000}
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION_MINUTES:10080}
    cookie:
      secure: ${COOKIE_SECURE:false}
      same-site: ${COOKIE_SAME_SITE:Lax}
