spring:
  application:
    name: olympic

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  mvc:
    problemdetails:
      enabled: true

  ai:
    model:
      chat: ${SPRING_AI_MODEL_CHAT:none}
      embedding:
        text: ${SPRING_AI_MODEL_EMBEDDING_TEXT:none}

server:
  servlet:
    context-path: /

logging:
  pattern:
    level: "%5p [traceId=%X{traceId:-}]"
